spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: circuit-breaker

client:
  comments:
    url: http://localhost:8082

resilience4j:
  circuitbreaker:
    instances:
      comments:
        sliding-window-size: 8
#        minimum-number-of-calls: 4
#        permitted-number-of-calls-in-half-open-state: 2
#        wait-duration-in-open-state: 10s
        slow-call-duration-threshold:
          seconds: 2
        slow-call-rate-threshold: 50