spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: circuit-breaker

client:
  comments:
    url: http://localhost:8082

resilience4j:
  circuitbreaker:
    instances:
      comments:
        sliding-window-size: 8
        minimum-number-of-calls: 4