version: "3.1"
services:
  mongo:
    image: mongo:6.0.6
    restart: always
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express:0.61.0  # Versão compatível com o MongoDB 6.0
    restart: always
    ports:
    - "8083:8083"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  redis-compose:
    image: redis
    command: redis-server
    hostname: redis
    ports:
      - "6379:6379"

networks:
  broker-kafka:
    driver: bridge
